### PR TITLE
Textfield style bugs

### LINKED ISSUE #241: Disabled fields design
### Bricks version 📦
0.6.0

### Describe the bug 🔍
The way disabled fields are displayed differs from the designs.

### Screenshots 📸
Top is design, bottom screen from storybook:
image

Link to abstract file: https://share.goabstract.com/116dfeac-67c0-47f1-a2d4-c8a32045425f
Specific layer in abstract: https://share.goabstract.com/d92ba9d9-10d8-4b76-8790-0f94294ce131

### PR DESCRIPTION
**Pull request by nicokoelewijn**
### This PR:

resolves #241 and #242

proposed release: `patch`

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable)
- [x] Appropriate tests have been added for my functionality (check if not applicable)
- [x] A designer has seen and approved my changes (check if not applicable)

**Changes** 🌀
- disabled knob added to `Textfield.numberFormatting`
- adjusted styling

### CODE REVIEW

**Comment by hborghols** [comment]
If the textfield is very small the lock and the text in the textfield get all tangled up:
screenshot 2018-10-31 at 17 17 29

**Comment by hborghols** [comment]
In the withNumber variant the lock gets superimposed on the buttons to change the number, this looks pretty messy:

screenshot 2018-10-31 at 17 19 16

**Comment by CarloPalinckx** [comment]
This would be a cool one to get a design sign-off on. Maybe you could wait for the now deployments (#248) so you can tag a designer with the deployed url

**Comment by nicokoelewijn** [comment]
> If the textfield is very small the lock and the text in the textfield get all tangled up:
> screenshot 2018-10-31 at 17 17 29

Sorry won't do. Inputfields should be large enough in usage that this doesn't occur. There are breakpoints that help achieve this.

**Comment by hborghols** [comment]
In safari there's whitespace between the background and the border in the disabled state:
screenshot 2018-11-07 at 11 44 08

**Comment by hborghols** [comment]
Prefix/suffix of withCurrency formatting are missing in safari, same issue as in IE (see #253) 😢

**Comment by nicokoelewijn** [comment]
> Prefix/suffix of withCurrency formatting are missing in safari, same issue as in IE (see #253) 😢

Turns out this is caused by a lack of an Intl polyfill, which causes the lack of a dollar sign. Perhaps it would be best to adres this in another branch?

**Pull request merged**
