### PR TITLE
feat!: Fileinput now keeps preview around on re-render

### PR DESCRIPTION
**Pull request by CarloPalinckx**
### This PR:

The FileInput currently does not support being re-rendered with a file, the file preview is removed once the FileInput is re-rendered. This PR solves this problem by lifting the ref of the image out of the component with the `value` prop. A ref is passed in that can have its current value read in the onChange callback.

**Breaking changes** 🔥
- The FileInput now requires a value prop to be set up in order to function
- Moved some props around to prevent nesting in the props

**Backwards compatible additions** ✨
- None

**Bugfixes/Changed internals** 🎈
- Added a test and a story to cover the preview behaviour

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable).
- [x] Appropriate tests have been added for my functionality (check if not applicable).
- [x] A designer has seen and approved my changes (tag `@LuukHorsmans` or `@RianneSchaekens` for a design review when applicable).
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).
- [x] Appropriate documentation has been written (check if not applicable).

<details>
  <summary>ℹ️ Conventional commit help</summary>

  - Use `fix: ...` for patches
  - Use `feat: ...` for a minor change
  - Use `feat!: ...` for features with breaking changes
  - Optionally you can use a scope `feat(SomeContainer)!: ...`
  - A breaking change **must** have `BREAKING CHANGE: ...` in the commit message
  - You can use multiple `BREAKING CHANGE: ...` lines in the commit message
  - Use `build`, `chore`, `ci`, `docs`, `perf`, `refactor`, `style`, or `test`  for other types

  More info see full [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).

  _Tip: make sure the first commit message is the one you want to merge, because that's the one Github picks for squashing._
</details>

### CODE REVIEW

**Comment by CarloPalinckx** [comment]
For the merge message:
> BREAKING CHANGE: FileInput now requires a ref to be passed into the value prop

**Review by woutsluiter — CHANGES_REQUESTED** [review]
Looking good! I noticed a small flash of the original preview prop image when you toggle the image. Is that because it's a fixed value in the story? 

One thing though: the `Disabled` story breaks with this change.
image

**Comment by CarloPalinckx** [comment]
The preview prop is often used as a fixed prop that you rarely adjust so this shouldn't be flashing. My guess would be due to the async behaviour of the FileReader. I'll look into it 👍

**Review by woutsluiter — CHANGES_REQUESTED** [review]
Now when I change the file in the `WithToggle` story it disappears the first time 🤔

**Comment by CarloPalinckx** [comment]
> Now when I change the file in the WithToggle story it disappears the first time 🤔

Aah because the ref changes after picking a file the props get recomputes. I memoized it which fixed it ✅

**Review by woutsluiter — APPROVED** [review]

**Pull request merged**
