### PR TITLE
feat(Notification): new Notification styling

### PR DESCRIPTION
**Pull request by woutsluiter**
### This PR:

adds the new Notification styling 🎨

**Breaking changes** 🔥
- Notification theme object

**Backwards compatible additions** ✨
- none

**Bugfixes/Changed internals** 🎈
- none

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable).
- [x] Appropriate tests have been added for my functionality (check if not applicable).
- [x] A designer has seen and approved my changes (tag `@LuukHorsmans` or `@RianneSchaekens` for a design review when applicable).
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).
- [x] Appropriate documentation has been written (check if not applicable).

### CODE REVIEW

**Comment by hborghols** [comment]
Code looks fine but I believe the Notifications should not stretch to the full width of the container but only be as wide as they need to be.

**Comment by woutsluiter** [comment]
Right, I only focused on the border. I'll look into it 👍

**Comment by woutsluiter** [comment]
@LuukHorsmans you like?

**Comment by woutsluiter** [comment]
😫

**Pull request merged**
