### PR TITLE
feat: Added esm bundles and bundling

### PR DESCRIPTION
**Pull request by CarloPalinckx**
### This PR:

**Backwards compatible additions** ✨
- bricks is now also exported as esm bundles, esm compatible tools can use this to properly codesplit bricks and bricks-assets

**Checklist** 🛡
- [x] I have exported my addition from `src/index.ts` (check if not applicable).
- [x] Appropriate tests have been added for my functionality (check if not applicable).
- [x] A designer has seen and approved my changes (tag `@LuukHorsmans` or `@RianneSchaekens` for a design review when applicable).
- [x] I have tested my addition in all supported browsers and for responsiveness (Chrome, Firefox, Safari, Edge, IE11 and mobile browsers).
- [x] Appropriate documentation has been written (check if not applicable).

### CODE REVIEW

**Comment by CarloPalinckx** [comment]
@hborghols mind that "react-is" was added as a dependency, you'd have to install that in your testing env to get it to work

**Comment by hborghols** [comment]
Looks like the now build breaks in `Spinner/story.tsx`. Strange that it breaks there but not in the CQ check.

**Comment by CarloPalinckx** [comment]
@hborghols fixed it! We now only check types on the files that actually get bundled 😓 and since stories aren't bundled... they slip through. Could add a step to check those as well some point in time.

**Comment by hborghols** [comment]
I can't get it to work in canopy yet... I don't see any errors but storybook keeps loading indefinitely (I installed react-is): 

image

**Comment by CarloPalinckx** [comment]
@hborghols how are you adding bricks? yarn link?

**Comment by hborghols** [comment]
> @hborghols how are you adding bricks? yarn link?

Ah yes, I should try the canary of course 🤦‍♂

**Comment by hborghols** [comment]
Works with the canary 👍

**Pull request merged**
